### ISSUE TITLE
Installation Guide?

### ISSUE THREAD

**Issue by caspar** [namsnath/KeystrokeDynamics#3]
Dear @namsnath, 

This looks like some excellent software. Could you add a section on installation and use to the README.md? (or just tell me here). I see some HTML files in the ~~backend~~ frontend/ folder. Do I have to host these?

Caspar

**Comment by namsnath** [comment]
Hi @caspar,
I'll add it to the Readme in a few days, thanks for bringing it to my attention, I'd missed it. 

For now, I'll list the steps here. 

For backend:
- Start a mongodb process (usually `mongod`)
- `npm i` to install the modules
- `node server.js` to start the server

For frontend:
Just opening `login.html` or `signup.html` and interacting should work
The backend links are hard-coded for use on localhost. Searching for `localhost:3001` in the JS files should bring it up. Change the domains in those files if you're hosting it somewhere and it would work. 

I'm not sure where you saw html files in the backend folder, might be a typo. And yes, those will need to be served if you're hosting it.

**Comment by Shivag1212** [comment]
How can I run it on windows plz explain

**Comment by namsnath** [comment]
> How can I run it on windows plz explain 

The process remains the same as mentioned above. 
You need to have a mongo service running, you'll have to figure out how to do that on Windows. 

You'll need Node and Mongo installed.
